# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UI_Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UI_Project
  pod 'Alamofire'
  pod 'lottie-ios'
  pod 'RealmSwift'
  pod 'Kingfisher'
  pod 'DynamicJSON'
  
  #Firebase
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

end
